
	<main>
		<section class="picture container">
			<h2>Lorem ipsum dolor sit amet.</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident, voluptate maiores ab esse delectus quae error doloribus repudiandae excepturi! Praesentium, veniam harum sapiente laudantium reiciendis aliquam itaque dolorum soluta possimus.</p>
			<div class="galery">
				<figure>
					<img src="img/galery1.jpg" alt="Private dining room">
					<figcaption>Can welcome up to 24 guests</figcaption>
				</figure>
				<figure>
					<img src="img/galery2.jpg" alt="Private dining room">
					<figcaption>Can welcome up to 18 guests</figcaption>
				</figure>
				<figure>
					<img src="img/galery3.jpg" alt="Private dining room">
					<figcaption>Can welcome up to 36 guests</figcaption>
				</figure>
				<figure>
					<img src="img/galery4.jpg" alt="Private dining room">
					<figcaption>Can welcome up to 50 guests</figcaption>
				</figure>
			</div>
		</section>
	</main>
