
    <form action="" method="POST">
     <fieldset>
     <legend>Ajoutez une nouvelle category</legend>
    <div>
        <label for="name">Nom de produit :</label>
        <input type="text" id="name" name="name">
    </div>
    <div>
        <label for="description">Description :</label>
        <input type="text" id="description" name="description">
    </div>
     <div class="button">
        <button type="submit">Ajouter</button>
    </div>
     </fieldset>
    </form>
</main>
