
		<section class="commande">
			<h2>Merci pour votre commande</h2>
			<table class=" table table-striped">
				<thead>
					<tr>
						<th colspan="4" ><p class="center">Votre commande</p></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Total</td>
						<td colspan="4"><?= number_format($total,2,'.',''); ?> €</td>
					</tr>
				</tbody>
			</table>
				<div class="paiement">
				<a href="paiement.php" class="cartBoutton">Passer au paiement</a>
 				</div>
	  
 		</section>
  
