
	<div class="container">
    <h3 class="text-center"><br>New Reservation</h3> 
   
	<?php	if(Session::isConnected()) {
		echo '<p class="text-white bg-dark text-center">Welcome '. $_SESSION['login']['firstname'] .', Create your reservation here!</p>';
		
	}
		?>
		<?php if(Session::isConnected()): ?>
    <form action="" method="POST">
     <fieldset> 
     <legend>Avis</legend>
     <div> 
   
          <label for="number">Commentaire</label> 
          <input type="text" name="comment" id="comment"/>
    </div>


	<h3 style="color: red"><?php echo $message ?></h3>
     <div class="button">
        <button type="submit">commenter</button>
    </div>
     </fieldset>
    </form>
    <?php else: ?>
    <p class="text-center text-danger"><br>You are currently not logged in!<br></p>
    <p class="text-center">In order to write a feedback you have to create an account!<br><br><p>  

    
    <?php endif; ?>
     </div>
</main>
