<div class="intro">
	<h1>Bienvenu dans notre restaurant</h1>
	<p>Lorem ipsum dolor sit amet, consectetuer adipiscing</p>
</div>
<section class="local  container">
	<h2>La malvasia resaturant</h2>
	<div class="row">
		<!--carousel-->
		<div class="col-sm"><br><br>
			<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
					<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
					<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
				</ol>
				<div class="carousel-inner imgcarousel">
					<div class="carousel-item active">
						<img class="d-block w-100" src="img/local.jpg" alt="First slide">
					</div>
					<div class="carousel-item">
						<img class="d-block w-100" src="img/local2.jpg" alt="Second slide">
					</div>
					<div class="carousel-item">
						<img class="d-block w-100" src="img/local.jpg" alt="Third slide">
					</div>
				</div>
				<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
           <span class="carousel-control-prev-icon" aria-hidden="true"></span>
           <span class="sr-only">Previous</span>
         </a>
				<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
           <span class="carousel-control-next-icon" aria-hidden="true"></span>
           <span class="sr-only">Next</span>
         </a>
			</div><br><br>
		</div>

		<!--end of carousel-->

		<div class="col-sm">
			<div class="arranging"><br>
				<hr>
				<h3>Our Story</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, nihil modi itaque quas vel architecto nesciunt maiores rem eos blanditiis eius nobis inventore dolore voluptatum reprehenderit. At, odio nobis quod.</p>
				<p>Exercitationem, repudiandae, eligendi dolores accusamus ex cupiditate alias sunt vero iste officiis cum possimus adipisci vel mollitia accusantium dolor dolore doloremque repellendus deleniti tempore earum rerum et dolorem minima ab?</p>


				<div class="clear"></div>
				<hr>
			</div>
		</div>
	</div><br>
	</div>
</section>
<div class="citation">
	<button><a href="reservation.php">Réserver votre table </a></button>
</div>
<section class="container">
	<h2>Special menus</h2>
	<div class="special">
		<article>
			<h3>Meat menu</h3>

			<img src="img/meat-menu.jpg" alt="meat-menu">

			<ul class="star">
				<li>Lorem ipsum dolordg .</li>
				<li>Laborum, magni facere.</li>
				<li>Consequuntur, nobis illo.</li>
				<li>Eveniet, deleniti, aliquid.</li>
				<li>At, delectus, laboriosam.</li>
			</ul>
			<a href="#" class="plus">See more</a>
		</article>
		<article>
			<h3>Fish menu</h3>
			<img src="img/fish-menu.jpg" alt="fish-menu">

			<ul class="star">
				<li>Lorem ipsum dolordsg .</li>
				<li>Laborum, magni facere.</li>
				<li>Consequuntur, nobis illo.</li>
				<li>Eveniet, deleniti, aliquid.</li>
				<li>At, delectus, laboriosam.</li>

			</ul>
			<a href="#" class="plus">See more</a>
		</article>
		<article>
			<h3>Vegetarian menu</h3>

			<img src="img/vegetarian-menu.jpg" alt="vegetarian-menu">

			<ul class="star">
				<li>Lorem ipsum dolordsg .</li>
				<li>Laborum, magni facere.</li>
				<li>Consequuntur, nobis illo.</li>
				<li>Eveniet, deleniti, aliquid.</li>
				<li>At, delectus, laboriosam.</li>

			</ul>
			<a href="#" class="plus">See more</a>
		</article>
	</div>
</section>
<div class=" citation">

</div>
<section class="SectionGalery">
	<h2 class="ppb_title"><span class="ppb_title_first">Images</span> Galleries</h2>
	<div class="galeryImg">
		<div class="div1"><img src="img/galeryimg/img1.jpg" alt="galery1"> </div>
		<div class="div2"><img src="img/galeryimg/img2.jpg" alt="galery2"> </div>
		<div class="div3"><img src="img/galeryimg/img3.jpg" alt="galery3"> </div>
		<div class="div4"><img src="img/galeryimg/slick2.jpg" alt="galery4"> </div>
		<div class="div5"><img src="img/galeryimg/img4.png" alt="galery5"> </div>
		<div class="div6"><img src="img/galeryimg/img6.jpg" alt="galery6"> </div>
		<div class="div7"><img src="img/galeryimg/img7.jpg" alt="galery7"> </div>
		<div class="div8"><img src="img/galeryimg/img9.jpg" alt="galery8"> </div>
	</div>
</section>
