<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="La Malvasia Restaurant, your new favourite restaurant !">
	<link rel="icon" href="img/icon.png" type="image/x-png" />
	<title>La Malvasia Restaurant</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" type="text/css" />
	<meta name="viewport" content="width=device-width , initiale-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/slick.css" />
	<link rel="stylesheet" type="text/css" href="css/slick-theme.css" />
	<link rel="stylesheet" href="css/style.css">
</head>

<body>
		<header>

		<nav class="navbar">
			<ul class="navbarUl">
				<li class="first"><a href="index.php" class="active">Accueil</a></li>
				<li class="second"><a href="about.php">About</a></li>
				<li class="third"><a href="product.php">Commander</a></li>
				<li class="four"><a href="#contact">Contact</a></li>
				<?php if(Session::isConnected() && $_SESSION['login']['role']): ?>
						<li class="fifth"><a href="addProduct.php">ajouter</a></li>
						<?php endif ; ?>

			</ul>
			<div class="flex">
				<a href="index.php">
						<img src="img/Logo-restaurant.PNG" alt="Logo de restaurant">
					</a>
					
				<?php 
    				if(Session::isConnected()): ?>
					
					<a href="logout.php"><span><i class="far fa-user"></i>logout</span></a>
					<?php 
    			else: ?>

					<a href="authentification.php"><span><i class="fas fa-user-circle"></i></span></a>
					<?php endif ; ?>
					<a href="cart.php"><i class="fas fa-shopping-bag"></i><span></span></a>
			</div>	
			
			
				
			<div class="menuBtn" id="hamburger">
				<div class="bar1"></div>
				<div class="bar2"></div>
				<div class="bar3"></div>
			</div>
		
		</nav>
	
	</header>
	<main class="container">
		<?= $pageContent ?>
	</main>
	<footer>
		<div>
			<aside class="font">
				<ul>
					<li>
						<i class="fas fa-phone-volume"></i>
						<span>Phone:</span>
						<p> 00000000</p>
					</li>
					<li>
						<i class="fas fa-map-marker-alt"></i>
						<span>Location:</span>
						<p> Lorem ipsum dolor sit amet</p>

					</li>
					<li>
						<i class="fas fa-envelope"></i>
						<span>Email:</span>
						<p> resaturant@gmail.com</p>
					</li>
				</ul>
			</aside>
		</div>


		<section class="restofooter">
			<div class="open">
				<aside>
					<span>Opening hours</span>
					<ul>
						<li>Monday: Closed</li>
						<li>Tue-Wed : 9am - 10pm</li>
						<li>Thu-Fri : 9am - 10pm</li>
						<li>Sat-Sun : 5pm - 10pm</li>
					</ul>
				</aside>
				<aside id="contact">
					<span>Contact</span>
					<address>
						<p>13 Christopher Street<br>
							New York,<br>
							NY 10014-3543</p>
						<p>+01 2000 800 9999</p>
					</address>
				</aside>
				<aside>
					<span>Social networks</span>
					<div class="reseaux">
						<a href="" class="fab fa-facebook-f"></a>
					</div>
				</aside>
			</div>
			<!-- end of .flex -->

			</div>
		</section>
	</footer>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
	<script type="text/javascript" src="js/carousel.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="js/dropdown.js"></script>
	<script type="module" src="js/localStorage/localStorage.js"></script>
	<script type="module" src="js/localStorage/displayCart.js"></script>
	<script type="module" src="js/localStorage/storage.js"></script>
	<script type="module" src="js/localStorage/events.js"></script>
	<script type="module" src="js/localStorage/remove.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="module" src="js/scripts_paiement.js"></script>
	
</body>

</html>
