<section>
     <h1> Payer votre Commande</h1>   
<form action="" method="POST" class="formP">
    <!--zone d'affichage des erreurs-->
    <div id="errors"></div>
    <!--zone pour identifier la personne-->
    <div class="labelP">
    <label for="nom">Nom sur la carte</label>
    <input id="cardholder-name" type="text" placeholder="Titulaire de la carte" class=my-input>
    </div>
    <!--formulaire de siaise du numéro de la carte-->
    <div class="labelP">
    <label for="card-element">Numéro de la carte</label>
    <div id="card-element" class="cardElement my-input"> </div>
    </div>
    <!--l'affiche des erreurs relatives au nuéro de carte-->
    <div id="card-errors" role="alert"></div>
    <!--bouton de validation-->
    <a  href="#" id="card-button" data-secret="<?= $intent->client_secret ?>" class="sumbit cartBoutton">
      Submit Payment
    </a>
</form>
</section>

        
        
  