<div class="container mixitup">
		<h1>Details of our menus</h1>
		<p class="select">Choose your main course according to your menu!</p>
		<div class="filter">
			<button data-filter="all">All</button>
			<button data-filter=".vorspeisen">Vorspeisen</button>
			<button data-filter=".suppen">Suppen</button>
			<button data-filter=".salat">Salat</button>
			<button data-filter=".pastagerichte">Pastagerichte</button>
			<button data-filter=".fischgerichte">Fischgerichte</button>
			<button data-filter=".pasta">Pasta</button>
			<button data-filter=".pizza">Pizza</button>
		</div> <!-- end of .filter -->
		<section class="special">
			<div class="mix vorspeisen">
			<?php foreach($products as $element):?>
				<?php if ($element["product_category_id"]==1) :?>
			<article>
				<h2><?= $element["name"]; ?></h2>
				<figure class="absolute">
				<img src="<?= $element["picture"]; ?>" alt="<?= $element["name"]; ?>">
					<figcaption>
						<div></div>
						<p class="prix"><?= number_format($element["price"],2,'.','') ?> €</p>
					</figcaption>
				</figure>
				<ul class="star">
					<li>
						<?= $element["description"]; ?>
					</li>

				</ul>
				<?php if(Session::isConnected() && $_SESSION['login']['role']): ?>
				<a href="remove.php?id=<?= $element["id"]; ?>" class="plus">Supprimer</a>
				<a href="price.php?id=<?= $element["id"]; ?>" class="plus">modifier le prix </a>
				<?php endif; ?>
				<?php if(Session::isConnected()): ?>
				<a href="#" class="plus add" data-id="<?= $element["id"]; ?>" data-price="<?= number_format($element["price"],2,'.','') ?>" data-name="<?= $element["name"]; ?> "data-picture="<?= $element["picture"]; ?>">Ajouter au panier</a>
			
				<?php endif; ?>
		
				<?php endif; ?>
				<?php endforeach; ?>
			</article>
		</div>
			<div class="mix suppen">
			<?php foreach($products as $element):?>
				<?php if ($element["product_category_id"]==2) :?>
			<article>
				<h2><?= $element["name"]; ?></h2>
				<figure class="absolute">
				<img src="<?= $element["picture"]; ?>" alt="<?= $element["name"]; ?>">

					<figcaption>
						<div></div>
						<p class="prix"><?= number_format($element["price"],2,'.','') ?> €</p>
					</figcaption>
				</figure>
				<ul class="star">
					<li>
						<?= $element["description"]; ?>
					</li>

				</ul>
				<?php if(Session::isConnected() && $_SESSION['login']['role']): ?>
				<a href="remove.php?id=<?= $element["id"]; ?>"class="plus">Supprimer</a>
				<a href="price.php?id=<?= $element["id"]; ?>"class="plus">modifier le prix </a>
				<?php endif; ?>
				<?php if(Session::isConnected()): ?>
				<a href="#" class="add plus" data-id="<?= $element["id"]; ?>" data-price="<?= number_format($element["price"],2,'.','') ?>" data-name="<?= $element["name"]; ?> "data-picture="<?= $element["picture"]; ?>">Ajouter au panier</a>
				
				<?php endif; ?>
		
				<?php endif; ?>
				<?php endforeach; ?>
				</article>
		</div>
			<div class="mix salat">
			<?php foreach($products as $element):?>
				<?php if ($element["product_category_id"]==3) :?>
			<article>
				<h2><?= $element["name"]; ?></h2>
				<figure class="absolute">
				<img src="<?= $element["picture"]; ?>" alt="<?= $element["name"]; ?>">

					<figcaption>
						<div></div>
						<p class="prix"><?= number_format($element["price"],2,'.','') ?> €</p>
					</figcaption>
				</figure>
				<ul class="star">
					<li>
						<?= $element["description"]; ?>
					</li>

				</ul>
				<?php if(Session::isConnected() && $_SESSION['login']['role']): ?>
				<a href="remove.php?id=<?= $element["id"]; ?>" class="plus">Supprimer</a>
				<a href="price.php?id=<?= $element["id"]; ?>" class="plus">modifier le prix </a>
				<?php endif; ?>
				<?php if(Session::isConnected()): ?>
				<a href="#" class="add plus" data-id="<?= $element["id"]; ?>" data-price="<?= number_format($element["price"],2,'.','') ?>" data-name="<?= $element["name"]; ?> "data-picture="<?= $element["picture"]; ?>">Ajouter au panier</a>
				
				<?php endif; ?>
		
				<?php endif; ?>
				<?php endforeach; ?>
			</article>
		</div>
			<div class="mix pastagerichte">
			<?php foreach($products as $element):?>
				<?php if ($element["product_category_id"]==4) :?>
			<article>
				<h2><?= $element["name"]; ?></h2>
				<figure class="absolute">
				<img src="<?= $element["picture"]; ?>" alt="<?= $element["name"]; ?>">

					<figcaption>
						<div></div>
						<p class="prix"><?= number_format($element["price"],2,'.','') ?> €</p>
					</figcaption>
				</figure>
				<ul class="star">
					<li>
						<?= $element["description"]; ?>
					</li>

				</ul>
				<?php if(Session::isConnected() && $_SESSION['login']['role']): ?>
				<a href="remove.php?id=<?= $element["id"]; ?>"class="plus">Supprimer</a>
				<a href="price.php?id=<?= $element["id"]; ?>" class="plus">modifier le prix </a>
				<?php endif; ?>
				<?php if(Session::isConnected()): ?>
				<a  href="#" class="add plus" data-id="<?= $element["id"]; ?>" data-price="<?= number_format($element["price"],2,'.','') ?>" data-name="<?= $element["name"]; ?> "data-picture="<?= $element["picture"]; ?>">Ajouter au panier</a>
	
				<?php endif; ?>
		
				<?php endif; ?>
				<?php endforeach; ?>
		</article>
		</div>	
		<div class="mix fischgerichte">
			<?php foreach($products as $element):?>
				<?php if ($element["product_category_id"]==5) :?>
			<article>
				<h2><?= $element["name"]; ?></h2>
				<figure class="absolute">
				<img src="<?= $element["picture"]; ?>" alt="<?= $element["name"]; ?>">

					<figcaption>
						<div></div>
						<p class="prix"><?= number_format($element["price"],2,'.','') ?> €</p>
					</figcaption>
				</figure>
				<ul class="star">
					<li>
						<?= $element["description"]; ?>
					</li>

				</ul>
				<?php if(Session::isConnected() && $_SESSION['login']['role']): ?>
				<a href="remove.php?id=<?= $element["id"]; ?>" class="plus">Supprimer</a>
				<a href="price.php?id=<?= $element["id"]; ?>" class="plus">modifier le prix </a>
				<?php endif; ?>
				<?php if(Session::isConnected()): ?>
				<a href="#" class="add plus" data-id="<?= $element["id"]; ?>" data-price="<?= number_format($element["price"],2,'.','') ?>" data-name="<?= $element["name"]; ?> "data-picture="<?= $element["picture"]; ?>">Ajouter au panier</a>
				<?php endif; ?>
		
				<?php endif; ?>
				<?php endforeach; ?>
			</article>
		</div>	
			<div  class="mix pizza">
			<?php foreach($products as $element):?>
				<?php if ($element["product_category_id"]==6) :?>
			<article>
				<h2><?= $element["name"]; ?></h2>
				<figure class="absolute">
				<img src="<?= $element["picture"]; ?>" alt="<?= $element["name"]; ?>">

					<figcaption>
						<div></div>
						<p class="prix"><?= number_format($element["price"],2,'.','') ?> €</p>
					</figcaption>
				</figure>
				<ul class="star">
					<li>
						<?= $element["description"]; ?>
					</li>

				</ul>
				<?php if(Session::isConnected() && $_SESSION['login']['role']): ?>
				<a href="remove.php?id=<?= $element["id"]; ?>" class="plus">Supprimer</a>
				<a href="price.php?id=<?= $element["id"]; ?>" class="plus">modifier le prix </a>
				<?php endif; ?>
				<?php if(Session::isConnected()): ?>
				<a href="#" class="plus add" data-id="<?= $element["id"]; ?>" data-price="<?= number_format($element["price"],2,'.','') ?>" data-name="<?= $element["name"]; ?> "data-picture="<?= $element["picture"]; ?>">Ajouter au panier</a>
				<?php endif; ?>

				<?php endif; ?>
				<?php endforeach; ?>
				</article>		
		</div>	
		</section>
	</div>
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="js/mixitup.min.js"></script>
	<script>
		let mixer = mixitup(".mixitup");
	</script>
	
</body>

</html>