<section class="formdesing">
    <div class="wrapper login">
        <div class="containerForm">
            <div class="col-left">
                <div class="login-text">
                    <h2>Welcome Back</h2>
                    <p>Create your account.</p>
                </div>
            </div>

            <div class="col-right">
                <div class="login-form">
                    <h2>Login</h2>
                    <form action="" method="POST">
                        <p>
                            <label for="prenom">Prénom :</label>
                            <input type="text" name="firstname" id="firstname" />
                        </p>
                        <p>
                            <label for="nom">Nom :</label>
                            <input type="text" name="lastname" id="lastname" />
                        </p>

                        <p>
                            <label for="numero">Numéro de téléphone:</label>
                            <input type="text" id="phonenumber" name="phonenumber">
                        </p>
                        <p>
                            <label for="mail">e-mail:</label>
                            <input type="email" id="mail" name="mail">
                        </p>

                        <p>
                            <label for="password">Mot de passe :</label>
                            <input type="password" name="password" id="password" />

                        </p>


                        <p>
                            <label for="news">Recevoir des newsletter </label>
                            <input type="checkbox" name="isnews" id="isnews">

                        </p>
                        <p>
                            <input type="submit" value="Sign In">
                        </p>

                    </form>
                </div>
            </div>

        </div>
    </div>
</section>
	