
	<div class="container">
    <h3 class="text-center"><br>New Reservation</h3> 
   
	<?php	if(Session::isConnected()) {
		echo '<p class="text-white bg-dark text-center">Welcome '. $_SESSION['login']['firstname'] .', Create your reservation here!</p>';
		
	}
		?>
		<?php if(Session::isConnected()): ?>
		
    <form action="" method="POST">
     <fieldset> 
     <legend>Réserver</legend>
     <h3 style="color: red"><?php echo $message ?></h3>
     <div> 
   
          <label for="number">Nomber :</label> 
          <input type="number" name="number" id="number" min="1 " max="20"/>
    </div>
    <div> 
        <label for="date">Veuillez saisir une date et une heure :</label>
		<input id="date" type="datetime-local" name="date">
    </div>
    <div>
	    
	</div>
	
     <div class="button">
        <button type="submit">Réserver</button>
    </div>
     </fieldset>
    </form>
    <?php else: ?>
    <p class="text-center text-danger"><br>You are currently not logged in!<br></p>
    <p class="text-center">In order to make a reservation you have to create an account!<br><br><p>  

    
    <?php endif; ?>
     </div>
</main>
	
</body>
</html>


