
        <section class = "bgcimage">
            <?php if(Session::isConnected()): ?>
            <h2>BOOK YOUR TABLE NOW</h2>
            
            	<?php echo'<p>Welcome '. $_SESSION['login']['firstname'] .', Create your reservation here!</p>';?>
            
            <div class = "img-container">
                <div class = "reserved-img"></div>

                <div class = "img-content">
                    <h3>Reservation</h3>
		<p><small><?php echo $message; ?></small></p>
		<form  method="POST" class="formrev">
			
				 <div class = "form-row">
                            <input type = "number" name="number" id="number" placeholder="How Many Persons?" min = "1">
                            <input id="date" type="date" name="date" value="date" class="from-input">
                            </div>
                        <div class = "form-row">
                            <select name = "time" id="time" class="from-select">
                                <option value = "hour-select">Select Hour</option>
                                <option value = "10">12: 00</option>
                                <option value = "10">12: 30</option>
                                <option value = "10">13: 00</option>
                                <option value = "10">13: 30</option>
                                <option value = "10">18: 30</option>
                                <option value = "10">19: 00</option>
                                <option value = "10">19: 30</option>
                                <option value = "10">20: 00</option>
                                <option value = "10">20: 30</option>
                                <option value = "10">21: 00</option>
                            </select>
                            
                            <input type = "submit" value = "BOOK TABLE">
                        </div>
                    </form>
                </div>
    
            </div>
        </section>
<?php else: ?>
    <p></p>You are currently not logged in!<br></p>
    <p class="text-center">In order to make a reservation you have to create an account!<p>  

    
    <?php endif; ?>
